[package]
name = "word_power"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = "0.24"
strum_macros = "0.24"
